site_name: LLM Gateway Core
site_url: https://github.com/LLM-Gateway-ORG/llm-gateway-core
repo_url: https://github.com/LLM-Gateway-ORG/llm-gateway-core
nav:
  - Getting Started: index.md
  - License: license.md
  - Supported Models: models_list.html
theme:
  name: material
  # logo: assets/hacker.png
  icon:
    repo: fontawesome/brands/git-alt

extra_files:
  - "models_list.json"

extra:
  plugins:
    - optimize
