name: Update Models List

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC
  workflow_dispatch: # Allows manual triggering

permissions:
    contents: write

jobs:
  update-models:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipreqs
          pipreqs . --force
          pip install -r requirements.txt

      # Step 4: Run the update script
      - name: Run model updater script
        run: python src/llmgateway/scripts/ai_models_updater.py

      # Step 5: Check and commit changes
      - name: Commit and push changes
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

          # Check if files exist before attempting to add them
          if [ -f "llmgateway/models_list.json" ] && [ -f "src/llmgateway/provider/litellm/models_list.json" ]; then
            git add llmgateway/models_list.json src/llmgateway/provider/litellm/models_list.json
          else
            echo "Required files do not exist. Skipping commit."
            exit 0
          fi

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
